### ISSUE TITLE
Could you please upload the "fastrcnn_feat.prototxt" file？

### ISSUE THREAD

**Issue by junleiz** [BryanPlummer/pl-clc#2]
Hello, I am very sorry to bother you. I wish to run your code to extract the visual features. But I can not find a place to download the fastrcnn_feat.prototxt" file. Could you please upload this file or Could you please tell me which layer (fc7 or fc7 relu) you used in your CITE paper? And Do Thank you very much!

**Comment by BryanPlummer** [comment]
This is part of the precomputed data.  You can download that archive and extract it from there.
